### ISSUE TITLE
Create React App Error WIth Bun

### ISSUE THREAD

**Issue by shinnthantminn** [AshirbadGudu/bun-react-app#1]
I am using create react app with bun js but show me this error 

`error: could not determine executable to run for package create-react`

### How Can i solve this

**Comment by birmehto** [comment]
i also have the save issue with bun

**Comment by kerosan** [comment]
looks its typo
try to use `react-app` instead of `react`

**Comment by amanda-shlee** [comment]
i'm also getting the same error on MacOS
`error: could not determine executable to run for package create-react` 

I've tried 
- `bun create react bun-bun-react `
- `bunx create-react bun-bun-react`
- `bun create react ./app`

**Comment by amanda-shlee** [comment]
i've found the solution. 
First, create a folder, e.g. `mkdir folder`
Then, run ` bunx create-react-app ./folder`

**Comment by kinyenzm** [comment]
Hello after typing `bun create react-app app_bun` I get this:

```
Creating a new React app in /home/user/react/app_bun

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...


Aborting installation.
Unexpected error. Please report it as a bug:
605 |   }
606 |   get stdio() {
607 |     return this.#stdioObject ??= this.#createStdioObject();
608 |   }
609 | 
610 |   spawn(options) {
                 ^
TypeError: Executable not found in $PATH: "npm"
 code: "ERR_INVALID_ARG_TYPE"

      at spawn (node:child_process:610:14)
      at node:child_process:2:40
      at spawn (/tmp/create-react-app@latest--bunx/node_modules/cross-spawn/index.js:12:20)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:383:18
      at new Promise (:1:20)
      at install (/tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:334:9)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:461:15
      at processTicksAndRejections (:61:76)


Deleting generated file... package.json
Deleting app_bun/ from /home/user/react/app_bun
Done.
```
I'm using wsl:deepin
